set_property SRC_FILE_INFO {cfile:E:/Vivado/projects/HDL_Project/HDL_Project.srcs/constrs_1/new/constraint.xdc rfile:../../../HDL_Project.srcs/constrs_1/new/constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L19  IOSTANDARD LVCMOS33 } [get_ports gpio_io_o_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD LVCMOS33 } [get_ports { gpio2_io_o_0[0] }]; # LED 0: CLOCKWISE
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R17 IOSTANDARD LVCMOS33 } [get_ports { gpio2_io_o_0[1] }]; # LED 1: ANTI-CLOCKWISE
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T19  IOSTANDARD LVCMOS33 } [get_ports uart_rtl_txd]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R19  IOSTANDARD LVCMOS33 } [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M19  IOSTANDARD LVCMOS33 } [get_ports Vaux2_0_v_p]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M20  IOSTANDARD LVCMOS33 } [get_ports Vaux2_0_v_n]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M17  IOSTANDARD LVCMOS33 } [get_ports Vaux10_0_v_p]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M18  IOSTANDARD LVCMOS33 } [get_ports Vaux10_0_v_n]
